### ISSUE TITLE
twidiscord: quota limit

### ISSUE THREAD

**Issue by diamondburned** [diamondburned/twikit#1]
It would be nice if twidiscord can have a quota limit for limiting the number of notifications sent over SMS:

```toml
[discord.quota]
person = 5
global = 50
```

This will prevent people from draining others' bank accounts.
